# Generated by Django 3.2.8 on 2021-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_blog', '0002_remove_blog_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='reposts',
            field=models.IntegerField(default=0),
        ),
    ]
